require(['angular', 'bootStrap'
  , 'controllers/index/serverCtrl'
  // , 'controllers/index/customListCtrl'
  // , 'controllers/index/groupCtrl'
  // , 'controllers/index/consultStatisticCtrl'
  // , 'controllers/index/usuallyCtrl'
  , 'controllers/index/groupEditCtrl'
  , 'controllers/index/messageCtrl'
  // , 'controllers/index/messageStatisticCtrl'
  // , 'controllers/index/journaledCtrl'
  // , 'controllers/index/questionLibraryCtrl'
  // , 'controllers/index/questionDetailCtrl'
  , 'controllers/index/questionManagementCtrl'
  , 'controllers/index/questionStatisticCtrl'
  , 'controllers/index/homeCtrl'
  , 'controllers/index/userManagementCtrl'
  // , 'controllers/index/regionStatisticsCtrl'
  , 'controllers/index/bannerExaminationAppCtrl'
  , 'controllers/index/informationListExaminationAppCtrl'
  , 'controllers/index/FeedbackExaminationAppCtrl'
  // , 'controllers/index/packageLabelCtrl'
  , 'controllers/index/commentCtrl'
  , 'controllers/index/serviceManagementCtrl'
  , 'controllers/index/icoManagementCtrl'
  , 'controllers/index/answersCtrl'
  , 'controllers/index/activityGroupCtrl'
  , 'controllers/index/systemSettingCtrl'
  , 'controllers/index/knowledgeStoreCtrl'
  // , 'controllers/index/dspPictureManageCtrl'
  // , 'controllers/index/doctorPowerCtrl'
  , 'controllers/index/DepartInfoCtrl'
  , 'controllers/index/mall/SupplierInfoCtrl'
  , 'controllers/index/mall/GoodsManagementCtrl'
  , 'controllers/index/mall/GoodsTypeCtrl'
  , 'controllers/index/mall/AppointmentCtrl'
  , 'controllers/index/mall/CouponManagementCtrl'
  , 'controllers/index/mall/enterpriseAppointmentCtrl'
  , 'controllers/index/mall/physicalExamEventQuotaCtrl'
  , 'controllers/index/mall/enterpriseStaffCtrl'
  , 'controllers/index/mall/PaybackCtrl'
  , 'controllers/index/mall/OrderCtrl'
  , 'controllers/index/mall/groupAppointManageCtrl'
  , 'controllers/index/mall/promoteOrderCtrl'
  , 'controllers/index/activePositionCtrl'
  , 'controllers/index/pushManagementCtrl'
  , 'controllers/index/mall/telAppointmentCtrl'
  , 'controllers/index/mall/goodsAddItemCtrl'
  , 'controllers/index/simpleServiceManagementCtrl'
],
  function (angular) {
    angular.element(document).ready(function () {
      angular.bootstrap(document, ['indexApp']);
    });
  });
